---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: 'weekly'
