# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - tests/demos
  skip-files:
    - ".*_demo\\.go$"

issues:
  exclude-rules:
    # Exclude demo files from certain linters
    - path: tests/demos/
      linters:
        - typecheck
        - deadcode
        - unused

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gocritic

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  staticcheck:
    checks: ["all"]
